# Generated by Django 5.0.3 on 2024-03-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineEnCasa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(default='static/img/country-flags/default-flag.png', upload_to='static/img/country-flags'),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(default='static/img/film-posters/default-film.png', upload_to='static/img/film-posters'),
        ),
    ]
