# Generated by Django 5.0.3 on 2024-03-18 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineEnCasa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='film',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CineEnCasa.filmtype'),
        ),
    ]
