# Generated by Django 5.0.3 on 2024-03-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineEnCasa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='film',
            name='platform',
        ),
        migrations.AddField(
            model_name='film',
            name='platform',
            field=models.ManyToManyField(null=True, to='CineEnCasa.platform'),
        ),
    ]
