# Generated by Django 5.0.3 on 2024-03-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineEnCasa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(default='flags/default.png', upload_to='country_flags'),
        ),
    ]
