# Generated by Django 5.0.3 on 2024-03-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineEnCasa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=4, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='language_version',
            field=models.ManyToManyField(to='CineEnCasa.languageversion'),
        ),
    ]
