# Generated by Django 5.0.3 on 2024-03-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineEnCasa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='hour',
            field=models.TimeField(default='20:00'),
        ),
    ]
