# Generated by Django 5.0.3 on 2024-03-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineEnCasa', '0002_film_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('ESP', 'Spain'), ('UK', 'United Kingdom'), ('JAP', 'Japan'), ('KO', 'Korea'), ('CAT', 'Catalonia'), ('IRE', 'Ireland')], max_length=20),
        ),
    ]
