# Generated by Django 5.0.3 on 2024-03-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineEnCasa', '0002_platform_remove_film_platform_film_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='platform',
            field=models.ManyToManyField(blank=True, to='CineEnCasa.platform'),
        ),
    ]
