# Generated by Django 5.0.3 on 2024-03-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineEnCasa', '0003_alter_film_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='color',
            field=models.CharField(default='#0000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='film',
            name='platform',
            field=models.ManyToManyField(to='CineEnCasa.platform'),
        ),
    ]
