# Generated by Django 5.0.3 on 2024-03-18 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineEnCasa', '0003_alter_billboardfilm_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('current_film', models.PositiveIntegerField(default=1)),
                ('total_films', models.PositiveIntegerField(default=2)),
                ('elem_type', models.CharField(max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='film',
            name='current_film',
        ),
        migrations.RemoveField(
            model_name='film',
            name='is_saga',
        ),
        migrations.RemoveField(
            model_name='film',
            name='saga_type',
        ),
        migrations.RemoveField(
            model_name='film',
            name='total_films',
        ),
        migrations.AddField(
            model_name='film',
            name='saga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CineEnCasa.saga'),
        ),
    ]
