# Generated by Django 5.0.3 on 2024-03-18 13:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineEnCasa', '0003_alter_film_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='is_series',
            new_name='is_saga',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='series_type',
            new_name='saga_type',
        ),
        migrations.RemoveField(
            model_name='film',
            name='current_movie',
        ),
        migrations.RemoveField(
            model_name='film',
            name='day',
        ),
        migrations.RemoveField(
            model_name='film',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='film',
            name='month',
        ),
        migrations.RemoveField(
            model_name='film',
            name='total_movies',
        ),
        migrations.AddField(
            model_name='film',
            name='current_film',
            field=models.PositiveIntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='film',
            name='total_films',
            field=models.PositiveIntegerField(default='3'),
        ),
        migrations.CreateModel(
            name='BillboardFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField(default='20:00')),
                ('day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('month', models.CharField(choices=[('JAN', 'Enero'), ('FEB', 'Febrero'), ('MAR', 'Marzo'), ('APR', 'Abril'), ('MAY', 'Mayo'), ('JUN', 'Junio'), ('JUL', 'Julio'), ('AUG', 'Agosto'), ('SEP', 'Septiembre'), ('OCT', 'Octubre'), ('NOV', 'Noviembre'), ('DEC', 'Diciembre')], max_length=10)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CineEnCasa.film')),
            ],
        ),
    ]
