# Generated by Django 5.0.3 on 2024-03-18 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CineEnCasa', '0004_saga_remove_film_current_film_remove_film_is_saga_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saga',
            name='elem_type',
        ),
    ]
