# Generated by Django 5.0.3 on 2024-03-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineEnCasa', '0006_alter_film_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saga',
            name='current_film',
        ),
        migrations.AddField(
            model_name='film',
            name='current_film',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(default='media/film-posters/default.png', upload_to='media/film-posters'),
        ),
        migrations.AlterField(
            model_name='saga',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
