# Generated by Django 5.0.3 on 2024-03-18 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CineEnCasa', '0007_remove_saga_current_film_film_current_film_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='current_film',
            new_name='current_saga_film',
        ),
    ]
